config/routes.rb
Omrails::Application.routes.draw do
  resources :pins

  devise_for :users

  get 'about' => 'pages#about'
  get 'hot' => 'pages#hot'
  get 'new' => 'pins#index'
  get 'near' => 'pages#near'
  get 'test' => 'pages#test'
  get 'projects' => 'pages#projects'
  get 'post' => 'pins#new'

 root :to => 'pins#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :image_remote_url


  validates :description, presence: true
  validates :user_id, presence: true
  has_attached_file :image, styles: { medium: "320x240>"}
  validates_attachment :image, presence: true,
                            content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                            size: { less_than: 5.megabytes }
  belongs_to :user
  
    def image_remote_url=(url_value)
    self.image = URI.parse(url_value) unless url_value.blank?
    super
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
   <div class="container">
      <div class="row">
       <div class="span12">
        <div id="footer">

           <ul class="footer">
           	<br>
			<hr></hr>
            <p> #BurgerMonster by Ilkka </p>
           <ul>

        </div>
     </div>
  </div>
</div>

app/views/layouts/_header.html.erb
 <div class="navbar navbar-fixed-top">
   <div class="navbar-inner">
    <div class="container">
     
    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </a>
     
    <!-- Be sure to leave the brand out there if you want it shown -->
    <%= link_to "#BurgerMonster", root_path, class: "brand", style: "color:orange" %>
     
    <!-- Everything you want hidden at 940px or less, place within here -->
 
        <% if user_signed_in? %>
   <div class="nav-collapse collapse">
        <ul class="nav"> 
           <li><%= link_to "New", root_path %></li>
            <li>  <%= link_to "Hot", hot_path %></li>
            <li><%= link_to "Near", near_path %></li>
     <!--Removed for now:
           <li><%= link_to "Projects", projects_path %></li>
           <li><%= link_to "Test", test_path %></li> -->
            <li><%= link_to "About", about_path %></li> 
            </ul>
            <ul class="nav pull-right">


         <li><%= link_to "My Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <li> <%= link_to "Upload", new_pin_path, style: "color:red" %> </li>

          
        <% else %>
   <div class="nav-collapse collapse">
        <ul class="nav"> 
            <li><a href="new.html#A">New</a><li>
            <li>  <%= link_to "Hot", hot_path %></li>
            <li><%= link_to "Near", near_path %></li>
     <!--Removed for now:
           <li><%= link_to "Projects", projects_path %></li>
           <li><%= link_to "Test", test_path %></li> -->
            <li><%= link_to "About", about_path %></li> 
            </ul>
            <ul class="nav pull-right">



    	   <li><%= link_to "Login", new_user_session_path %></li>
           <li><%= link_to "Sign up", new_user_registration_path %></li>
           <li> <%= link_to "Upload", new_pin_path, style: "color:red" %> </li>
        <% end %>
			</ul>
    <!-- .nav, .navbar-search, .navbar-form, etc -->
    </div>
    </div>
    </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>#BurgerMonster</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
            <% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
            <% end %>
            <%= yield %>
			<%= render 'layouts/footer' %>	

	</body>
</html>

app/views/pages/_home.html.erb
<% if user_signed_in? %>

<div class="row">
    	<div class="span2">
    	</div>
    	
    	<div class="span2">
    		<div class="pull-right">
			<br><br><br>
				<img src="https://dl.dropboxusercontent.com/u/38177869/pig_monster_newmini.jpg"> 
		</div> 
		</div> 


    	<div class="span4">
		<div class="jumbotron">
				<h1> NEW <br> BURGERS </h1>
				<p class="lead">
					@ #BurgerMonster
				</p>
		</div>
		</div>
		
		
		<div class="span4">
		</div>
</div>


<% else %>


  <div class="hero-unit">
    <div class="row-fluid">
        <div class="columnA pull-right">
        	<br>
             <h1>SHOW ME THE BURGER</h1>
            <p> <br>
            <font size="6">SHARE, RATE & EAT THE BEST BURGERS IN WORLD</font>
		</p>
		<br>
		<p>	<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-success btn-large" %>
			 <a href="#A"> <button class="btn btn-warning btn-large"> Check 'em Burgers</button></a>
			 <br>  Already have an account? 
           <%= link_to "Log in now ", new_user_registration_path, style: "color:red" %>
		</p>
        </div>

        <div class="columnB pull-left">
            <img src="https://dl.dropboxusercontent.com/u/38177869/pig_monster_single%20copy.jpg">
        </div>
    </div>
  </div>

<img class="displayed" src="https://dl.dropboxusercontent.com/u/38177869/arrow2.jpg">

<a name="A"> <hr class="featurette-divider"></hr></a>

<div class="jumbotron">
	<h1> NEW <br> BURGERS </h1>
	<p class="lead">
  @ #BurgerMonster
</p>
</div>

<% end %>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
  <body>
<!--  Carousel - consult the Twitter Bootstrap docs at 
      http://twitter.github.com/bootstrap/javascript.html#carousel -->
<div id="this-carousel-id" class="carousel slide"><!-- class of slide for animation -->
<div class="carousel-inner">
    <div class="item active"><!-- class of active since it's the first item -->
      <img src="http://falconinvesting.com/files/2012/01/falcon-Investing-slide-1-1200x480.png" alt="" />
        <div class="container">
          <div class="carousel-caption">
        <h1 style="color:white"> Awesome </h1>
        <p class="lead"> Would you want be here? </p> <br>
<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-success" %>      </div>
    </div>
  </div>

    <div class="item">
      <img src="http://shadowness.com/file/item3/79750/image.jpg" alt="" />
      <div class="container">
          <div class="carousel-caption">
        <h1 style="color:white"> Cool </h1>
        <p class="lead"> Would you want be here?</p> <br>
        <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-success" %>
      </div>
    </div>
 </div>
 
    <div class="item">
      <img src="http://habitatresidence.com/site/wp-content/uploads/2012/12/habitat-slider-1-1200x480.jpg" alt="" />
      <div class="container">
          <div class="carousel-caption">
        <h1 style="color:white"> Wow </h1>
        <p class="lead"> Would you want be here?</p> <br>
        <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-success" %>
      </div>
    </div>
  </div>

    <div class="item">
      <img src="http://merlelor.com/wp-content/uploads/2012/12/Roemeni%C3%A2-2006_5245-15-8-2006-19-03-45a-1200x480.jpg" alt="" />
      <div class="container">
          <div class="carousel-caption">
        <h1 style="color:white"> Nice </h1>
        <p class="lead"> Would you want be here?</p> <br>
        <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div> <!-- /.carousel-inner -->

  <!--  Next and Previous controls below
        href values must reference the id for this carousel -->
    <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->

  <script>
      $(document).ready(function(){
        $('.carousel').carousel({
          interval: 4000
        });
      });
    </script>
<hr class="featurette-divider"></hr>

<div class="container marketing">
<div class="featurette">
<img class="featurette-image pull-right" src="http://www.mwss.ca/upload_image/crocodile.gif"></img>
<br><br><br><br>
<h2 class="featurette-heading">First featurette headling. 
  <span class="muted">
      It'll blow your mind. </span>
</h2>
<p class="lead">
      Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
    </p></div>

<br><br><br><br><br><br><br><br><br><br><br>
    <hr class="featurette-divider"></hr>

<div class="container marketing">
<div class="featurette">
<img class="featurette-image pull-left" src="http://ecx.images-amazon.com/images/I/51ex7c5UGPL._SS500_.jpg"></img>
<br><br><br><br>
<h2 class="featurette-heading">First featurette headling. 
  <span class="muted">
      It'll blow your mind. </span>
</h2>
<p class="lead">
      Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
    </p></div>

  <br><br><br><br><br><br><br><br><br><br><br>
    <hr class="featurette-divider"></hr>

<div class="container marketing">
<div class="featurette">
<img class="featurette-image pull-right" src="http://openclipart.org/people/bocian/owl_ebook.svg"></img>
<br><br><br><br>
<h2 class="featurette-heading">First featurette headling. 
  <span class="muted">
      It'll blow your mind. </span>
</h2>
<p class="lead">
      Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
    </p></div>

     <br><br><br><br><br><br><br><br><br><br><br>
    <hr class="featurette-divider"></hr>


  </body>
</html>

app/views/pages/hot.html.erb
<div class="row">
    	<div class="span2">
    	</div>
    	
    	<div class="span2">
    		<div class="pull-right">
			<br>
				<img src="https://dl.dropboxusercontent.com/u/38177869/pig_monster_hotmini.jpg"> 
		</div> 
		</div> 


    	<div class="span4">
		<div class="jumbotron">
				<h1> HOT<br> BURGERS </h1>
				<p class="lead">
					@ #BurgerMonster
				</p>
		</div>
		</div>

app/views/pages/near.html.erb
<div class="row">
    	<div class="span2">
    	</div>
    	
    	<div class="span2">
    		<div class="pull-right">
			<br><br><br>
				<img src="https://dl.dropboxusercontent.com/u/38177869/pig_monster_nearmini.jpg"> 
		</div> 
		</div> 


    	<div class="span4">
		<div class="jumbotron">
				<h1> NEAR <br> BURGERS </h1>
				<p class="lead">
					@ #BurgerMonster
				</p>
		</div>
		</div>

app/views/pages/new.html.erb
<div class="jumbotron">
<h1> New Burgers </h1>
<p class="lead">
	@ #BurgerMonster
</p>
</div>

app/views/pages/projects.html.erb
<!DOCTYPE html>
<html lang="en">
  <body>
<!--  Carousel - consult the Twitter Bootstrap docs at 
      http://twitter.github.com/bootstrap/javascript.html#carousel -->
<div id="this-carousel-id" class="carousel slide"><!-- class of slide for animation -->
<div class="carousel-inner">
    <div class="item active"><!-- class of active since it's the first item -->
      <img src="http://falconinvesting.com/files/2012/01/falcon-Investing-slide-1-1200x480.png" alt="" />
        <div class="container">
          <div class="carousel-caption">
        <h1 style="color:white"> Check out this project. </h1>
        <p class="lead"> Would you want be here? </p> <br>
        <a class="btn btn-primary" href="#"> Sign Up! </a>
      </div>
    </div>
  </div>

    <div class="item">
      <img src="http://shadowness.com/file/item3/79750/image.jpg" alt="" />
      <div class="container">
          <div class="carousel-caption">
        <h1 style="color:white"> Check out this project. </h1>
        <p class="lead"> Would you want be here?</p> <br>
        <a class="btn btn-primary" href="#"> Sign Up! </a>
      </div>
    </div>
 </div>
 
    <div class="item">
      <img src="http://habitatresidence.com/site/wp-content/uploads/2012/12/habitat-slider-1-1200x480.jpg" alt="" />
      <div class="container">
          <div class="carousel-caption">
        <h1 style="color:white"> Check out this project. </h1>
        <p class="lead"> Would you want be here?</p> <br>
        <a class="btn btn-primary" href="#"> Sign Up! </a>
      </div>
    </div>
  </div>

    <div class="item">
      <img src="http://merlelor.com/wp-content/uploads/2012/12/Roemeni%C3%A2-2006_5245-15-8-2006-19-03-45a-1200x480.jpg" alt="" />
      <div class="container">
          <div class="carousel-caption">
        <h1 style="color:white"> Check out this project. </h1>
        <p class="lead"> Would you want be here?</p> <br>
        <a class="btn btn-primary" href="#"> Sign Up! </a>
      </div>
    </div>
  </div>
</div> <!-- /.carousel-inner -->

  <!--  Next and Previous controls below
        href values must reference the id for this carousel -->
    <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->

 	<script>
    	$(document).ready(function(){
        $('.carousel').carousel({
          interval: 4000
        });
      });
    </script>
<hr class="featurette-divider"></hr>

<div class="container marketing">
<div class="featurette">
<img class="featurette-image pull-right" src="http://www.mwss.ca/upload_image/crocodile.gif"></img>
<br><br><br><br>
<h2 class="featurette-heading">First featurette headling. 
  <span class="muted">
      It'll blow your mind. </span>
</h2>
<p class="lead">
      Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
    </p></div>

<br><br><br><br><br><br><br><br><br><br><br>
    <hr class="featurette-divider"></hr>

<div class="container marketing">
<div class="featurette">
<img class="featurette-image pull-left" src="http://ecx.images-amazon.com/images/I/51ex7c5UGPL._SS500_.jpg"></img>
<br><br><br><br>
<h2 class="featurette-heading">First featurette headling. 
  <span class="muted">
      It'll blow your mind. </span>
</h2>
<p class="lead">
      Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
    </p></div>

  <br><br><br><br><br><br><br><br><br><br><br>
    <hr class="featurette-divider"></hr>

<div class="container marketing">
<div class="featurette">
<img class="featurette-image pull-right" src="http://openclipart.org/people/bocian/owl_ebook.svg"></img>
<br><br><br><br>
<h2 class="featurette-heading">First featurette headling. 
  <span class="muted">
      It'll blow your mind. </span>
</h2>
<p class="lead">
      Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
    </p></div>

     <br><br><br><br><br><br><br><br><br><br><br>
    <hr class="featurette-divider"></hr>


  </body>
</html>

app/views/pages/test.html.erb
<!DOCTYPE html>
<html lang="en">
  <body>
<!--  Carousel - consult the Twitter Bootstrap docs at 
      http://twitter.github.com/bootstrap/javascript.html#carousel -->
<div id="this-carousel-id" class="carousel slide"><!-- class of slide for animation -->
  <div class="carousel-inner">
    <div class="item active"><!-- class of active since it's the first item -->
      <img src="http://falconinvesting.com/files/2012/01/falcon-Investing-slide-1-1200x480.png" alt="" />
      <div class="carousel-caption">
        <p>Would you want be here?</p>
      </div>
    </div>

    <div class="item">
      <img src="http://shadowness.com/file/item3/79750/image.jpg" alt="" />
      <div class="carousel-caption">
        <p>We are already here.</p>
      </div>
    </div>

    <div class="item">
      <img src="http://habitatresidence.com/site/wp-content/uploads/2012/12/habitat-slider-1-1200x480.jpg" alt="" />
      <div class="carousel-caption">
        <p>Come and join us.</p>
      </div>
    </div>
    
    <div class="item">
      <img src="http://merlelor.com/wp-content/uploads/2012/12/Roemeni%C3%A2-2006_5245-15-8-2006-19-03-45a-1200x480.jpg" alt="" />
      <div class="carousel-caption">
        <p>Live Now!</p>
      </div>
    </div>
  </div><!-- /.carousel-inner -->
  <!--  Next and Previous controls below
        href values must reference the id for this carousel -->
    <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Be One of the First.</h2>
           <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>No more hassel.</h2>
           <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Say Yes.</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
      </div>

    </div> <!-- /container -->

 	<script>
    	$(document).ready(function(){
        $('.carousel').carousel({
          interval: 4000
        });
      });
    </script>
  </body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

      <%= f.input :image, label: "Upload an image" %>
      <%= f.input :image_remote_url, label: "or enter URL" %>
      <%= f.input :description, as: :text, input_html: { rows: "3" } %>

 <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
	<%= link_to (image_tag pin.image(:medium)), pin %>
<p class="description">
	<%= pin.description %>
</p>
<p>
 <strong>
	Burger by <%= pin.user.name %>
 </strong>
</p>
    <% if current_user == pin.user %>
<p>
    <%= link_to 'Edit', edit_pin_path(pin), style:"color:orange" %>
    <%= link_to 'Destroy', pin, style:"color:orange", method: :delete, data: { confirm: 'Are you sure?' } %>
</p>
    <% end %>
 </div>

app/views/pins/edit.html.erb
<div class="container marketing">
	<div class="featurette">

		<h2 class="featurette-heading"> EDIT THE BURGER </h2>
		     	<br>
	</div>	    
</div>


<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

<div id="pins">
  <%= render @pins %>
</div>

app/views/pins/new.html.erb
<div class="container marketing">
	<div class="featurette">

		<h2 class="featurette-heading"> POST A BURGER </h2>
		<p class="lead">
		      Share the burger you love!
		     	<br>
		   </p>
	</div>	    
</div>



<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
    <div class="span6 offset3">
        <div class="well">
            <%= image_tag @pin.image %>
            <p>
              <%= @pin.description %>
            </p>
            <p>
              <%= @pin.user.name %>
            </p>
            <% if current_user == @pin.user %>
                <%= link_to 'Edit', edit_pin_path(@pin) %> |
            <% end %>
            <%= link_to 'Back', pins_path %>
        </div>
    </div>
</div>